name: Build pdfs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build dtool ecosystem pdf
        working-directory: latex/ecosystem
        run: |
          pdflatex ecosystem_dtool.tex

      - name: Build dserver ecosystem pdf
        working-directory: latex/ecosystem
        run: |
          pdflatex ecosystem_dserver.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Upload entire repository
          path: |
            latex/ecosystem/ecosystem_dtool.pdf
            latex/ecosystem/ecosystem_dserver.pdf
         
